///////////////////////////////////////////////////////////
//  AlarmRespResultData.cs
//  Implementation of the Class AlarmRespResultData
//  Generated by Enterprise Architect
//  Created on:      21-4-2015 오후 10:55:51
//  Original author: ahnyj ahnyj
///////////////////////////////////////////////////////////




using Business.NCasType;
namespace NCasPDbManager.DataContainers {
	/// <summary>
	/// 미리올라온 응답정보를 담는 데이터 클래스
	/// </summary>
	public class AlarmRespResultData : NCasObject {

		/// <summary>
		/// 응답/결과 시각
		/// </summary>
		private DateTime respResultTime = null;
		/// <summary>
		/// 발령대상지역
		/// </summary>
		private int areaCode;
		private int broadCtrlFlag;
		/// <summary>
		/// 발령구분
		/// </summary>
		private int section;
		/// <summary>
		/// 경보종류
		/// </summary>
		private int alarmKind;
		/// <summary>
		/// 발령매체
		/// </summary>
		private int media;
		/// <summary>
		/// 단말코드
		/// </summary>
		private int devCode;
		/// <summary>
		/// 단말종류
		/// </summary>
		private int devKind;
		/// <summary>
		/// 발령원
		/// </summary>
		private int source;
		/// <summary>
		/// 응답/결과 여부
		/// </summary>
		private int respResultFlag;

		public AlarmRespResultData(){

		}

		~AlarmRespResultData(){

		}

		public override NCasObject CopyTo(){

			return null;
		}

		/// <summary>
		/// 응답/결과 시각
		/// </summary>
		public DateTime RespResultTime{
			get{
				return respResultTime;
			}
			set{
				respResultTime = value;
			}
		}

		/// <summary>
		/// 발령대상지역
		/// </summary>
		public int AreaCode{
			get{
				return areaCode;
			}
			set{
				areaCode = value;
			}
		}

		public int BroadCtrlFlag{
			get{
				return broadCtrlFlag;
			}
			set{
				broadCtrlFlag = value;
			}
		}

		/// 
		/// <param name="obj"></param>
		public override void CopyFrom(NCasObject obj){

		}

		/// <summary>
		/// 발령구분
		/// </summary>
		public int Section{
			get{
				return section;
			}
			set{
				section = value;
			}
		}

		/// <summary>
		/// 경보종류
		/// </summary>
		public int AlarmKind{
			get{
				return alarmKind;
			}
			set{
				alarmKind = value;
			}
		}

		/// <summary>
		/// 발령매체
		/// </summary>
		public int Media{
			get{
				return media;
			}
			set{
				media = value;
			}
		}

		/// <summary>
		/// 단말코드
		/// </summary>
		public int DevCode{
			get{
				return devCode;
			}
			set{
				devCode = value;
			}
		}

		/// <summary>
		/// 단말종류
		/// </summary>
		public int DevKind{
			get{
				return devKind;
			}
			set{
				devKind = value;
			}
		}

		/// <summary>
		/// 발령원
		/// </summary>
		public int Source{
			get{
				return source;
			}
			set{
				source = value;
			}
		}

		/// <summary>
		/// 응답/결과 여부
		/// </summary>
		public int RespResultFlag{
			get{
				return respResultFlag;
			}
			set{
				respResultFlag = value;
			}
		}

	}//end AlarmRespResultData

}//end namespace DataContainers