///////////////////////////////////////////////////////////
//  BasicDataMng.cs
//  Implementation of the Class BasicDataMng
//  Generated by Enterprise Architect
//  Created on:      18-4-2015 오후 1:54:40
//  Original author: ahnyj ahnyj
///////////////////////////////////////////////////////////




using Foundation.NCasDb;
namespace NCasPDbManager.BasicDataMngContainers {
	/// <summary>
	/// 기초데이터를 불러와서 관리하는 클래스
	/// </summary>
	public class BasicDataMng {

		/// <summary>
		/// 장비정보를 담고 있는 딕셔너리
		/// </summary>
		private static Dictionary<string, MasterInfoData> dicMasterInfoData = new Dictionary<string, MasterInfoData>();
		/// <summary>
		/// 이전시간
		/// </summary>
		private static DateTime oldTime;
		/// <summary>
		/// NCasOracleDb
		/// </summary>
		private static NCasOracleDb oralceDb = null;
		/// <summary>
		/// DBClose동기화 객체
		/// </summary>
		private static Object closeObject = new Object();

		public BasicDataMng(){

		}

		~BasicDataMng(){

		}

		/// <summary>
		/// 데이터베이스 연결을 종료한다.
		/// </summary>
		public static void CloseDataBase(){

			//lock(closeObject)
			//{
			//if(oracleDb != null)
			//}


		}

		/// <summary>
		/// 타이머 이벤트
		/// </summary>
		public static void ProcTimer(){

			//lock(oldTime)
			//{
			//if(CheckTimeOut(oldTime, DateTime.Now(),
			//0,0, 20))
			//CloseDataBase();
			//}


		}

		/// <summary>
		/// 데이터베이스를 오픈하고 NcasOracleDb를 반환한다.
		/// </summary>
		public static NCasOracleDb OpenDataBase(){

			//lock(oldTime)
			//{
			//oldTime=DateTime.Now();
			//}


			return null;
		}

		/// <summary>
		/// IP를 넘겨받아 해당하는 MasterInfoData를 반환한다.
		/// </summary>
		/// <param name="ip"></param>
		public static MasterInfoData GetMasterInfoDataToIp(string ip){

			return null;
		}

		/// <summary>
		/// 발령원이 시도일 경우 해당 시도의 code값을 반환한다.
		/// </summary>
		/// <param name="ip"></param>
		/// <param name="source"></param>
		public static int GetAlarmAreaProvCode(string ip, int source){

			return 0;
		}

		/// <summary>
		/// 세션과 IP를 넘겨받아 해당 방송단말 MasterInfoData를 반환한다.
		/// </summary>
		/// <param name="section"></param>
		/// <param name="ip"></param>
		public static MasterInfoData GetBroadMasterInfoData(int section, string ip){

			return null;
		}

		/// <summary>
		/// 세션과 IP를 넘겨받아 해당 경보단말 MasterInfoData를 반환한다.
		/// </summary>
		/// <param name="section"></param>
		/// <param name="ip"></param>
		public static MasterInfoData GetAlarmMasterInfoData(int section, string ip){

			return null;
		}

		/// <summary>
		/// 소멸자
		/// </summary>
		public static void Uninit(){

		}

		/// <summary>
		/// MasterInfo데이터를 불러온다.
		/// </summary>
		private static void LoadMasterInfoData(){

			//dicMasterInfoData.Add();


		}

		/// <summary>
		/// 초기화함수
		/// </summary>
		public static void Init(){

			//LoadMasterInfoData();


		}

		/// <summary>
		/// 장비정보를 담고 있는 딕셔너리
		/// </summary>
		public Dictionary<string, MasterInfoData> DicMasterInfoData{
			get{
				return dicMasterInfoData;
			}
			set{
				dicMasterInfoData = value;
			}
		}

	}//end BasicDataMng

}//end namespace BasicDataMngContainers