///////////////////////////////////////////////////////////
//  ConfigViewKind.cs
//  Implementation of the Enumeration ConfigViewKind
//  Generated by Enterprise Architect
//  Created on:      17-4-2015 오후 5:27:59
//  Original author: ahnyj ahnyj
///////////////////////////////////////////////////////////




namespace NCasPDbManager.ConfigContainers {
	/// <summary>
	/// Config화면에서 각 화면의 Kind를 정의한다.
	/// </summary>
	public enum ConfigViewKind : int {

		/// <summary>
		/// 없음
		/// </summary>
		None = 0,
		/// <summary>
		/// 데이터베이스 접속 설정
		/// </summary>
		dbConfig = 1,
		/// <summary>
		/// TCP 프로파일 설정 화면
		/// </summary>
		tcpConfig = 2,
		/// <summary>
		/// UDP설정 화면
		/// </summary>
		udpConfig = 3

	}//end ConfigViewKind

}//end namespace ConfigContainers