///////////////////////////////////////////////////////////
//  MainForm.cs
//  Implementation of the Class MainForm
//  Generated by Enterprise Architect
//  Created on:      17-4-2015 오후 3:16:30
//  Original author: ahnyj ahnyj
///////////////////////////////////////////////////////////




using NCasPDbManager.DBManagerBizContainers;
using Foundation.NCasDb;
using NCasPDbManager.BasicDataMngContainers;
using NCasPDbManager;
namespace NCasPDbManager {
	/// <summary>
	/// 메인화면
	/// </summary>
	public class MainForm {

		/// <summary>
		/// DBManager 비지니스 로직
		/// </summary>
		private DbManagerBiz dbManagerBiz = null;
		/// <summary>
		/// 타이머
		/// </summary>
		private Timer mainTimer = null;
		public NCasPDbManager.DBManagerBizContainers.DbManagerBiz m_DbManagerBiz;



		~MainForm(){

		}

		/// <summary>
		/// 생성자
		/// </summary>
		public MainForm(){

			//ConfigMng.Init();
			//if(CheckDataBase())
			//this.Close();
			//BasicDataMng.Init();


		}

		/// <summary>
		/// 타이머
		/// </summary>
		public void OnTimer(){

			//BasicDataMng.ProcTimer();
			//SetProcessingStandbyCount();


		}

		/// <summary>
		/// 타이머를 멈춘다.
		/// </summary>
		private void TimerStop(){

		}

		/// <summary>
		/// 타이머를 시작한다.
		/// </summary>
		private void TimerStart(){

		}

		/// <summary>
		/// 처리해야하는 카운트를 화면에 표시한다.
		/// </summary>
		private void SetProcessingStandbyCount(){

			//dbManagerBiz.GetProcessingCount();
			//dbManagerBiz.GetStandbyCount();


		}

		/// <summary>
		/// 데이터베이스에 연결이 가능한지 확인한다.
		/// </summary>
		/// <param name="isClose"></param>
		private bool CheckDataBase(bool isClose){

			//bool isClose=false;
			//NCasOracleDb oracleDb=null;
			//ConfigForm configForm = null;
			//while(true){
			//oracleDb.Open(ConfigMng.Ip...);
			//if(oracleDb.IsOpen())
			//isClose=false; break;
			//configForm=new ConfigForm();
			//if(configForm.
			//ShowDialog()==DialogResult.Cancel)
			//isClose=true; break;}
			//return isClose;


			return false;
		}

		/// <summary>
		/// profile과 연결상태를 입력받아 화면에 표시한다.
		/// </summary>
		/// <param name="nCasProfile"></param>
		/// <param name="isConnect"></param>
		public void SetProfileStatus(NCasProfile nCasProfile, bool isConnect){

		}

		/// <summary>
		/// 종료 이벤트
		/// </summary>
		/// <param name="args"></param>
		protected void OnClosing(CancelEventArgs args){

			//TimerStop();
			//NCasBizActivator.Inactive();
			//dbManagerBiz.UnInit();


		}

		/// <summary>
		/// 시작 이벤트
		/// ***생성자에서 Close할때 다른것을 Init하지 못하게 처리해야함
		/// </summary>
		/// <param name="args"></param>
		protected void OnLoad(EventArgs args){

			//NCasBizActivator.
			//Active(NCasDefineActivatorCode.ForProv);
			//
			//dbManagerBiz.Init();


		}

	}//end MainForm

}//end namespace NCasPDbManager