///////////////////////////////////////////////////////////
//  TcpProfileData.cs
//  Implementation of the Class TcpProfileData
//  Generated by Enterprise Architect
//  Created on:      17-4-2015 오후 5:04:02
//  Original author: ahnyj ahnyj
///////////////////////////////////////////////////////////




using Business.NCasType;
namespace NCasPDbManager.DataContainers {
	/// <summary>
	/// TCP연결에 필요한 Profile을 관리하는 데이터 클래스
	/// </summary>
	public class TcpProfileData : NCasObject {

		/// <summary>
		/// TCP통신에 사용되는 NCasProfile
		/// </summary>
		private NCasProfile profile = null;
		/// <summary>
		/// 연결대상 이름
		/// </summary>
		private string connectName = string.Empty;

		public TcpProfileData(){

		}

		~TcpProfileData(){

		}

		public override NCasObject CopyTo(){

			return null;
		}

		/// <summary>
		/// TCP통신에 사용되는 NCasProfile
		/// </summary>
		public NCasProfile Profile{
			get{
				return profile;
			}
			set{
				profile = value;
			}
		}

		/// <summary>
		/// 연결대상 이름
		/// </summary>
		public string ConnectName{
			get{
				return connectName;
			}
			set{
				connectName = value;
			}
		}

		/// 
		/// <param name="obj"></param>
		public override void CopyFrom(NCasObject obj){

		}

	}//end TcpProfileData

}//end namespace DataContainers